#
# Configuration file for planning using sliding
# Modified from planning_config.yaml
# To cope with 2 sliders cases
# 

dynamics:
    xLenght: 0.07
    yLenght: 0.12
    pusherRadious: 0.01 #  [meter]
    pusherFricCoef: 0.2
    pusherForceLim:  0.45
    pusherAngleVelLim: 3.0
    pusherVelLim: 0.2 #  [m/s]
    Ks_max: 50.
    Ks_min: 50.
    Kx_max: 10.
    xFacePsiLimit: 0.9

TO:
    contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # contactMode: 'sliding_mi'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    contactFace: '-x'  # '+x', '-x', '+y', '-y'
    solverName: 'ipopt'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    # solverName: 'knitro'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [0.0, 1.0, 1.0, 1.0, 1.0, 0.01]  # diagonal state weights
    W_u: [0.01, 0.01]  # diagonal control weights
    K_goal: 100.
    X_goal: null
    numObs: 0
    # X_goal: null
    linDynFlag: False
    codeGenFlag: False
    noPrintingFlag: False
    phases: null
